---
- name: "IPv4 forward"
  hosts: ipv4router
  become: yes
  gather_facts: False
  tasks:
  - name: "Set net.ipv4_ip_forward=1"
    ansible.posix.sysctl:
      name: net.ipv4.ip_forward
      value: '1'
      sysctl_set: true
      state: present
      reload: true
      sysctl_file: /etc/sysctl.d/20-ipv4-forward.conf
