---
- name: "Upgrade servers"
  hosts: all
  become: yes
  tasks:
  - name: "Ubuntu upgrade"
    when: (ansible_distribution == "Ubuntu")
    apt: update_cache=yes upgrade=yes autoremove=yes

  - name: "Fedora upgrade"
    when: (ansible_distribution == "Fedora")
    dnf: update_cache=yes autoremove=yes

  - name: Check if reboot required
    stat:
      path: /var/run/reboot-required
    register: reboot_required_file

  - reboot:
    when: reboot_required_file.stat.exists == true
