---
- name: "Upgrade Debian based servers"
  hosts: debian
  become: yes
  gather_facts: False
  strategy: free

  tasks:
  - name: "apt upgrade"
    apt: update_cache=yes upgrade=yes

  - name: Check if reboot required
    stat:
      path: /var/run/reboot-required
    register: reboot_required_file

  - reboot:
    when: reboot_required_file.stat.exists == true
